import PDFDocument from 'pdfkit';

const colors = { ink: '#17312d', muted: '#60756e', brand: '#347f73', line: '#cfddd5' };

function printable(value) {
  if (value === null || value === undefined || value === '') return 'Not available';
  if (value instanceof Date) return value.toLocaleDateString();
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

function label(key = '') {
  return key.replace(/([A-Z])/g, ' $1').replaceAll('_', ' ').replace(/^./, (character) => character.toUpperCase());
}

function ensureSpace(doc, height = 35) {
  if (doc.y + height > doc.page.height - 55) doc.addPage();
}

function renderValue(doc, key, value, depth = 0) {
  if (['reportId', 'roadmapId', 'sourceId', '_id', 'rawText', 'redactedText', 'filePublicId'].includes(key)) return;
  const inset = depth * 12;
  const width = doc.page.width - 104 - inset;
  ensureSpace(doc);
  if (Array.isArray(value)) {
    doc.font('Helvetica-Bold').fontSize(10).fillColor(colors.ink).text(label(key), 52 + inset, doc.y, { width });
    if (!value.length) doc.font('Helvetica').fillColor(colors.muted).text('No records available.', 64 + inset, doc.y, { width: width - 12 });
    for (const item of value.slice(0, 30)) {
      ensureSpace(doc);
      if (item && typeof item === 'object') {
        const summary = item.name || item.skillName || item.title || item.label || item.role || JSON.stringify(item);
        doc.font('Helvetica').fontSize(9).fillColor(colors.muted).text(`• ${summary}`, 64 + inset, doc.y, { width: width - 12 });
      } else {
        doc.font('Helvetica').fontSize(9).fillColor(colors.muted).text(`• ${printable(item)}`, 64 + inset, doc.y, { width: width - 12 });
      }
    }
    doc.moveDown(0.35);
    return;
  }
  if (value && typeof value === 'object') {
    doc.font('Helvetica-Bold').fontSize(11).fillColor(colors.brand).text(label(key), 52 + inset, doc.y, { width });
    for (const [childKey, childValue] of Object.entries(value)) renderValue(doc, childKey, childValue, depth + 1);
    return;
  }
  doc.font('Helvetica-Bold').fontSize(9).fillColor(colors.muted).text(`${label(key)}: `, 52 + inset, doc.y, { continued: true, width });
  doc.font('Helvetica').fillColor(colors.ink).text(printable(value), { width });
}

export function createReportPdf(report, studentName = '') {
  const doc = new PDFDocument({ size: 'A4', bufferPages: true, margins: { top: 48, bottom: 48, left: 52, right: 52 } });
  doc.font('Helvetica-Bold').fontSize(20).fillColor(colors.brand).text('Skill Gap Intelligence Platform');
  doc.font('Helvetica').fontSize(12).fillColor(colors.muted).text(report.title || 'Student Report');
  doc.moveDown(0.6).strokeColor(colors.line).moveTo(52, doc.y).lineTo(543, doc.y).stroke().moveDown(0.7);
  if (studentName) renderValue(doc, 'studentName', studentName);
  renderValue(doc, 'generatedAt', report.generatedAt || new Date());
  for (const [key, value] of Object.entries(report)) {
    if (['title', 'type', 'generatedAt', 'studentName'].includes(key)) continue;
    renderValue(doc, key, value);
  }
  const range = doc.bufferedPageRange();
  for (let page = range.start; page < range.start + range.count; page += 1) {
    doc.switchToPage(page);
    doc.page.margins.bottom = 0;
    doc.font('Helvetica').fontSize(8).fillColor(colors.muted).text(
      `Generated by Skill Gap Intelligence Platform  •  Page ${page + 1}`,
      52, doc.page.height - 28, { width: doc.page.width - 104, align: 'center', lineBreak: false },
    );
  }
  return doc;
}
