export const seededCareerRoles = [
  {
    title: 'Data Scientist',
    aliases: ['ML Scientist', 'Applied Data Scientist'],
    category: 'Data & AI',
    description: 'Build predictive models, derive insights from data, and communicate findings that drive product and business decisions.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'Python', category: 'Programming', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Machine Learning', category: 'AI', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Statistics', category: 'Data', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'SQL', category: 'Data', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Data Visualization', category: 'Analytics', importance: 'Medium', minimumLevel: 'Beginner' },
    ],
    preferredSkills: [
      { name: 'Pandas', category: 'Data' },
      { name: 'Scikit-learn', category: 'AI' },
      { name: 'Experimentation', category: 'Analytics' },
    ],
    roadmapHints: ['Build an end-to-end ML project', 'Practice SQL on analytical datasets', 'Publish a model evaluation case study'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Data Analyst',
    aliases: ['Business Data Analyst', 'Analytics Analyst'],
    category: 'Data & AI',
    description: 'Transform raw data into dashboards, reports, and recommendations for stakeholders.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'SQL', category: 'Data', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Excel', category: 'Analytics', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Data Visualization', category: 'Analytics', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Statistics', category: 'Data', importance: 'Medium', minimumLevel: 'Beginner' },
      { name: 'Communication', category: 'Professional', importance: 'Medium', minimumLevel: 'Intermediate' },
    ],
    preferredSkills: [
      { name: 'Power BI', category: 'Analytics' },
      { name: 'Tableau', category: 'Analytics' },
      { name: 'Python', category: 'Programming' },
    ],
    roadmapHints: ['Create a stakeholder dashboard portfolio', 'Document metric definitions clearly', 'Practice storytelling with data'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Machine Learning Engineer',
    aliases: ['ML Engineer', 'AI ML Engineer'],
    category: 'Data & AI',
    description: 'Operationalize ML systems, ship models into production, and maintain reliable training and inference pipelines.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'Python', category: 'Programming', importance: 'High', minimumLevel: 'Advanced' },
      { name: 'Machine Learning', category: 'AI', importance: 'High', minimumLevel: 'Advanced' },
      { name: 'MLOps', category: 'AI', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Docker', category: 'Cloud', importance: 'Medium', minimumLevel: 'Intermediate' },
      { name: 'APIs', category: 'Backend', importance: 'Medium', minimumLevel: 'Intermediate' },
    ],
    preferredSkills: [
      { name: 'Kubernetes', category: 'Cloud' },
      { name: 'TensorFlow', category: 'AI' },
      { name: 'PyTorch', category: 'AI' },
    ],
    roadmapHints: ['Deploy one ML model as an API', 'Automate evaluation and retraining', 'Learn model monitoring basics'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'AI Engineer',
    aliases: ['Artificial Intelligence Engineer', 'Generative AI Engineer'],
    category: 'Data & AI',
    description: 'Design AI-powered applications that combine LLMs, automation, and domain-specific workflows.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'Python', category: 'Programming', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'NLP', category: 'AI', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Prompt Engineering', category: 'AI', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'APIs', category: 'Backend', importance: 'Medium', minimumLevel: 'Intermediate' },
      { name: 'System Design', category: 'Architecture', importance: 'Medium', minimumLevel: 'Beginner' },
    ],
    preferredSkills: [
      { name: 'Vector Databases', category: 'AI' },
      { name: 'LangChain', category: 'AI' },
      { name: 'Evaluation Frameworks', category: 'AI' },
    ],
    roadmapHints: ['Build one retrieval-augmented app', 'Measure output quality systematically', 'Practice prompt and schema design'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Backend Developer',
    aliases: ['Backend Engineer', 'Server-side Developer'],
    category: 'Software Engineering',
    description: 'Build scalable services, APIs, and data layers that power product experiences.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'Node.js', category: 'Backend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Express.js', category: 'Backend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'REST API', category: 'Backend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'MongoDB', category: 'Data', importance: 'Medium', minimumLevel: 'Intermediate' },
      { name: 'SQL', category: 'Data', importance: 'Medium', minimumLevel: 'Beginner' },
    ],
    preferredSkills: [
      { name: 'System Design', category: 'Architecture' },
      { name: 'Redis', category: 'Backend' },
      { name: 'Testing', category: 'Quality' },
    ],
    roadmapHints: ['Ship a production-style API', 'Add logging, validation, and tests', 'Design one scalable backend workflow'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Frontend Developer',
    aliases: ['UI Developer', 'Frontend Engineer'],
    category: 'Software Engineering',
    description: 'Create performant, accessible, and polished interfaces for web applications.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'JavaScript', category: 'Frontend', importance: 'High', minimumLevel: 'Advanced' },
      { name: 'React', category: 'Frontend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'HTML', category: 'Frontend', importance: 'High', minimumLevel: 'Advanced' },
      { name: 'CSS', category: 'Frontend', importance: 'High', minimumLevel: 'Advanced' },
      { name: 'Accessibility', category: 'Frontend', importance: 'Medium', minimumLevel: 'Beginner' },
    ],
    preferredSkills: [
      { name: 'TypeScript', category: 'Frontend' },
      { name: 'Tailwind CSS', category: 'Frontend' },
      { name: 'Testing', category: 'Quality' },
    ],
    roadmapHints: ['Build a responsive design system', 'Improve accessibility and motion quality', 'Create one polished portfolio app'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Full Stack Developer',
    aliases: ['Fullstack Developer', 'Full Stack Engineer'],
    category: 'Software Engineering',
    description: 'Own features across frontend, backend, and data layers with strong product awareness.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'React', category: 'Frontend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Node.js', category: 'Backend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'APIs', category: 'Backend', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'MongoDB', category: 'Data', importance: 'Medium', minimumLevel: 'Beginner' },
      { name: 'Git', category: 'Professional', importance: 'Medium', minimumLevel: 'Intermediate' },
    ],
    preferredSkills: [
      { name: 'TypeScript', category: 'Frontend' },
      { name: 'Docker', category: 'Cloud' },
      { name: 'Testing', category: 'Quality' },
    ],
    roadmapHints: ['Build one end-to-end deployed product', 'Add auth, persistence, and monitoring', 'Practice debugging across the stack'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'DevOps Engineer',
    aliases: ['Platform Engineer', 'Dev Ops Engineer'],
    category: 'Cloud & Infrastructure',
    description: 'Automate infrastructure, deployment pipelines, and operational reliability for engineering teams.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'Linux', category: 'Infrastructure', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Docker', category: 'Cloud', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'CI/CD', category: 'Infrastructure', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'AWS', category: 'Cloud', importance: 'Medium', minimumLevel: 'Beginner' },
      { name: 'Scripting', category: 'Programming', importance: 'Medium', minimumLevel: 'Intermediate' },
    ],
    preferredSkills: [
      { name: 'Kubernetes', category: 'Cloud' },
      { name: 'Terraform', category: 'Infrastructure' },
      { name: 'Monitoring', category: 'Infrastructure' },
    ],
    roadmapHints: ['Automate one deployment pipeline', 'Containerize a full-stack app', 'Practice observability basics'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Cloud Engineer',
    aliases: ['Cloud Platform Engineer'],
    category: 'Cloud & Infrastructure',
    description: 'Build and manage secure cloud platforms, services, and deployment environments.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'AWS', category: 'Cloud', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Networking', category: 'Infrastructure', importance: 'High', minimumLevel: 'Beginner' },
      { name: 'Linux', category: 'Infrastructure', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Docker', category: 'Cloud', importance: 'Medium', minimumLevel: 'Beginner' },
      { name: 'Security Basics', category: 'Security', importance: 'Medium', minimumLevel: 'Beginner' },
    ],
    preferredSkills: [
      { name: 'Terraform', category: 'Infrastructure' },
      { name: 'Kubernetes', category: 'Cloud' },
      { name: 'Cost Optimization', category: 'Cloud' },
    ],
    roadmapHints: ['Deploy multi-service apps on cloud infrastructure', 'Practice IAM and networking setup', 'Document cloud architecture decisions'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
  {
    title: 'Cybersecurity Analyst',
    aliases: ['Security Analyst', 'Cyber Security Analyst'],
    category: 'Security',
    description: 'Monitor threats, investigate incidents, and improve an organization’s security posture.',
    experienceLevel: 'Entry Level',
    requiredSkills: [
      { name: 'Networking', category: 'Security', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Linux', category: 'Security', importance: 'High', minimumLevel: 'Beginner' },
      { name: 'Security Fundamentals', category: 'Security', importance: 'High', minimumLevel: 'Intermediate' },
      { name: 'Incident Response', category: 'Security', importance: 'Medium', minimumLevel: 'Beginner' },
      { name: 'Risk Assessment', category: 'Security', importance: 'Medium', minimumLevel: 'Beginner' },
    ],
    preferredSkills: [
      { name: 'SIEM Tools', category: 'Security' },
      { name: 'Threat Hunting', category: 'Security' },
      { name: 'Python', category: 'Programming' },
    ],
    roadmapHints: ['Practice log analysis and alert triage', 'Learn common web security issues', 'Document incident response playbooks'],
    source: 'seeded',
    reviewStatus: 'approved',
  },
];

